[workspace]
members = ["crates/client", 
           "tests/compatibility-tests",
           "tests/integration-tests",
           "crates/native-tls",
           "crates/openssl",
           "crates/proto",
           "crates/resolver",
           "crates/rustls",
           "crates/https",
           "crates/server",
           "util"]
